import tkinter as tk
def click(event):
    global scvalue
    text=event.widget.cget("text")
    if text == "=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            try:
                value=eval(screen.get())
            except Exception as e:
                print(e)
                value= "Error"
        scvalue.set(value)
        screen.update()
    elif text == "C":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
root=tk.Tk()
root.geometry("500x600")
root.title("Calculator by Subhankit")
root.wm_iconbitmap("2.ico")
scvalue=tk.StringVar()
scvalue.set("")
screen=tk.Entry(root,textvariable=scvalue,font="lucida 40 bold")
screen.pack(fill=tk.X,padx=10,pady=10,ipadx=8)
f = tk.Frame(root,bg="grey")
b=tk.Button(f,text="9",font="lucida 30 bold",padx=5,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
b=tk.Button(f,text="8",font="lucida 30 bold",padx=5,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
b=tk.Button(f,text="7",font="lucida 30 bold",padx=5,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
f.pack()

f = tk.Frame(root,bg="grey")
b=tk.Button(f,text="6",font="lucida 30 bold",padx=5,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
b=tk.Button(f,text="5",font="lucida 30 bold",padx=5,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
b=tk.Button(f,text="4",font="lucida 30 bold",padx=5,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
f.pack()

f = tk.Frame(root,bg="grey")
b=tk.Button(f,text="3",font="lucida 30 bold",padx=5,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
b=tk.Button(f,text="2",font="lucida 30 bold",padx=5,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
b=tk.Button(f,text="1",font="lucida 30 bold",padx=5,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
f.pack()

f = tk.Frame(root,bg="grey")
b=tk.Button(f,text="0",font="lucida 30 bold",padx=5,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
b=tk.Button(f,text="-",font="lucida 30 bold",padx=9,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
b=tk.Button(f,text="*",font="lucida 30 bold",padx=8,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
f.pack()

f = tk.Frame(root,bg="grey")
b=tk.Button(f,text="/",font="lucida 30 bold",padx=10,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
b=tk.Button(f,text="%",font="lucida 30 bold",padx=0,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
b=tk.Button(f,text="=",font="lucida 30 bold",padx=3,pady=5)
b.pack(side=tk.LEFT,padx=2,pady=2)
b.bind("<Button-1>",click)
f.pack()

root.mainloop()
